#GET http://localhost:5000/api/movies/
#GET http://localhost:5001/api/movies/

#GET http://localhost:5000/api/movies/1
#GET http://localhost:5001/api/movies/1

#GET http://localhost:5000/api/movies/2
#GET http://localhost:5001/api/movies/2

#GET http://localhost:5000/api/movies/3
#GET http://localhost:5001/api/movies/3

#GET http://localhost:5000/api/movies/4
#GET http://localhost:5001/api/movies/4


#GET http://localhost:5000/api/users/
#GET http://localhost:5001/api/users/


GET http://localhost:5000/api/users/1
#GET http://localhost:5001/api/users/1


#GET http://localhost:5000/api/users/2
#GET http://localhost:5001/api/users/2

#GET http://localhost:5000/api/wishlist
#GET http://localhost:5001/api/wishlist


